adding test logger

diff --git a/ui/bin/wrf4g_framework b/ui/bin/wrf4g_framework
--- a/ui/bin/wrf4g_framework
+++ b/ui/bin/wrf4g_framework
@@ -1,31 +1,40 @@
 #! /bin/bash
 
-# wrf4g_framewok: start and stop the GridWay and MySQL components of WRF4G.
+# wrf4g_framewok manages GridWay and MySQL components of WRF4G.
 
 if test -z $WRF4G_LOCATION; then
-   echo '$WRF4G_LOCATION variable not established. Please export WRF4G_LOCATION and try again'
+   echo -e "\$WRF4G_LOCATION variable not established. Please export WRF4G_LOCATION and try again"
    exit 1
 fi
 
 if test -f $WRF4G_LOCATION/etc/framework4g.conf; then
    FRAMEWORK4G_CONF="$WRF4G_LOCATION/etc/framework4g.conf"
 else
-   echo '$WRF4G_LOCATION/etc/framework4g.conf does not exist'
+   echo -e "$WRF4G_LOCATION/etc/framework4g.conf does not exist"
    exit 1
 fi
-
 
 export GW_LOCATION=$WRF4G_LOCATION/opt/drm4g_gridway
 export MYSQL_LOCATION=$WRF4G_LOCATION/opt/mysql-5.5
 export PATH=$GW_LOCATION/bin:$PATH
-export LD_LIBRARY_PATH=$WRF4G_LOCATION/lib/shared_libs:$LD_LIBRARY_PATH
 
+function check_logger(){ 
+  files_to_test ="drm4g/im_drm4g.ini drm4g/em_drm4g.ini drm4g/tm_drm4g.ini vcp/vcp.ini" 
+  for file in ${files_to_test}; do
+    if test -f ${WRF4G_LOCATION}/var/${file}; then
+      sed -i "s#\$WRF4G_LOCATION#$WRF4G_LOCATION#" ${WRF4G_LOCATION}/var/${file}
+    else
+      echo -e "WARNING:  ${WRF4G_LOCATION}/var/${file} does not exist"
+    fi
+  done
+}
 
 case "$1" in
     start)
-	echo -n "Starting GridWay......."
+        check_logger
+        echo -n "Starting GridWay ...."
         grep '://' $FRAMEWORK4G_CONF > $GW_LOCATION/etc/hosts_drm4g.list
-        sed -e 's/\ *=\ */=/' ${WRF4G_LOCATION}/etc/resources.wrf4g | sed -e "s#\$WRF4G_LOCATION#$WRF4G_LOCATION#" >temp; cp temp ${WRF4G_LOCATION}/etc/resources.wrf4g; rm temp
+        sed -e 's/\ *=\ */=/' ${WRF4G_LOCATION}/etc/resources.wrf4g | sed -i "s#\$WRF4G_LOCATION#$WRF4G_LOCATION#"
         sed -i "s#\$HOSTNAME#$HOSTNAME#" $FRAMEWORK4G_CONF
 
         if test -f $GW_LOCATION/var/.lock; then
@@ -35,41 +44,42 @@ case "$1" in
         gwd
         st=$?
         if test $st -ne 0; then 
-           echo -e "FAILED. \nProblems starting GridWay $st"
-           exit 2 
+          echo -e "FAILED. \nProblems starting GridWay $st"
+          exit 2 
         fi
 	echo "  OK"
 
         grep "DB_.*=" ${WRF4G_LOCATION}/etc/framework4g.conf | sed -e 's/\ *=\ */=/' > db4g.conf.temp
         source db4g.conf.temp
         if [ $WRF4G_DB_LOCAL -eq 1 ]; then
-	   cd $MYSQL_LOCATION
-	   echo -n "Starting MySQL ......."
+	  cd $MYSQL_LOCATION
+	  echo -n "Starting MySQL ...."
 
-           if test -f $MYSQL_LOCATION/data/`hostname`.pid; then
-              mysql_pid=$(cat $MYSQL_LOCATION/data/`hostname`.pid)
-              if test $(ps -p $mysql_pid | grep -m1 -c $mysql_pid) -eq 1; then
-                echo -e "FAILED.\nMySQL already running. Run \"$(basename $0) stop\" to stop it"
-                exit 3
-              fi
-           fi
-           if [ $(netstat -atn |grep LISTEN | grep -m1 -c ":$WRF4G_DB_PORT ") -eq 1 ]; then
-               echo -e "FAILED.\nAnother process is listening on port $WRF4G_DB_PORT.\nChange WRF4G_DB_PORT in \$WRF4G_LOCATION/etc/framework4g.conf to start MySQL on a different port."
-               exit 4         
-           fi
+          if test -f $MYSQL_LOCATION/data/`hostname`.pid; then
+            mysql_pid=$(cat $MYSQL_LOCATION/data/`hostname`.pid)
+            if test $(ps -p $mysql_pid | grep -m1 -c $mysql_pid) -eq 1; then
+              echo -e "FAILED.\nMySQL already running. Run \"$(basename $0) stop\" to stop it"
+              exit 3
+            fi
+          fi
+          if [ $(netstat -atn |grep LISTEN | grep -m1 -c ":$WRF4G_DB_PORT ") -eq 1 ]; then
+            echo -e "FAILED.\nAnother process is listening on port $WRF4G_DB_PORT."
+            echo -e "Change WRF4G_DB_PORT in $WRF4G_LOCATION/etc/framework4g.conf to start MySQL on a different port."
+            exit 4         
+          fi
 	   
-           nohup ./bin/mysqld_safe --no-defaults --port=$WRF4G_DB_PORT --socket=$MYSQL_LOCATION/data/mysql.sock &>/dev/null &
-           cd - &>/dev/null
-       	   echo " OK"
-         fi
-         sed 's/WRF4G_DB_LOCAL.*/# DataBase Configuration/' db4g.conf.temp >${WRF4G_LOCATION}/etc/db4g.conf
-         rm db4g.conf.temp   
-       ;;
+          nohup ./bin/mysqld_safe --no-defaults --port=$WRF4G_DB_PORT --socket=$MYSQL_LOCATION/data/mysql.sock &>/dev/null &
+          cd - &>/dev/null
+       	  echo " OK"
+        fi
+        sed 's/WRF4G_DB_LOCAL.*/# DataBase Configuration/' db4g.conf.temp >${WRF4G_LOCATION}/etc/db4g.conf
+        rm db4g.conf.temp   
+        ;;
     stop)
 	echo -n "Stopping GridWay ...."
 	rm -f $GW_LOCATION/var/.lock
         if test ! -f $GW_LOCATION/var/gwd.port; then
-          echo -e "FAILED. \nGridWay already stopped. Run \"$(basename $0) start\" to run it" 
+          echo "FAILED. \nGridWay already stopped. Run \"$(basename $0) start\" to run it" 
           exit 2
           fi
         gwd_port=$(cat $GW_LOCATION/var/gwd.port  | awk '{print $2}')
@@ -80,7 +90,7 @@ case "$1" in
         grep "DB_.*=" ${WRF4G_LOCATION}/etc/framework4g.conf | sed -e 's/\ *=\ */=/' > db4g.conf.temp
         source db4g.conf.temp; rm db4g.conf.temp
         if [ $WRF4G_DB_LOCAL -eq 1 ]; then
-	  echo -n "Stopping MySQL ...."
+	  echo "Stopping MySQL ...."
           if test ! -f $MYSQL_LOCATION/data/`hostname`.pid; then
             echo -e "FAILED. \nMySQL already stopped. Run \"$(basename $0) start\" to run it" 
             exit 2
@@ -89,7 +99,7 @@ case "$1" in
           if test -n "`ps h -p $mysql_pid`" ; then 
             mysql_ppid=$(ps h -p $mysql_pid -o ppid)
 	    if test -n $mysql_ppid; then kill -9 $mysql_ppid ;fi
-	    if test -n $mysql_pid ; then  kill -9 $mysql_pid ;fi
+	    if test -n $mysql_pid ; then kill -9 $mysql_pid ;fi
           fi
 	  echo "  OK"
         fi
@@ -101,11 +111,9 @@ case "$1" in
         $0 start
         ;;
     reload)
+        check_logger
         # Only reloads gridway
-   	echo -n "Reloading GridWay ...."
-        grep '://' $FRAMEWORK4G_CONF > $GW_LOCATION/etc/hosts_drm4g.list
-        sed -e 's/\ *=\ */=/' ${WRF4G_LOCATION}/etc/resources.wrf4g | sed -e "s#\$WRF4G_LOCATION#$WRF4G_LOCATION#" >temp; cp temp ${WRF4G_LOCATION}/etc/resources.wrf4g; rm temp
-        sed -i "s#\$HOSTNAME#$HOSTNAME#" $FRAMEWORK4G_CONF
+   	echo "Reloading GridWay ...."
         gwd_port=$(cat $GW_LOCATION/var/gwd.port  | awk '{print $2}')
         gwd_pid=$(netstat -atnp 2>/dev/null | grep gwd | grep $gwd_port | awk '{print $7}'| sed s#/gwd##)
         if test -n "$gwd_pid"; then  
@@ -140,8 +148,8 @@ case "$1" in
           fi
         fi
         ;;
-    *)
-      cat << EOF
+         *)
+        cat << EOF
 USAGE 
   $(basename $0) {start|stop|restart|status|reload}
 
